# Generated by Django 6.0 on 2025-12-24 16:34

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Discount name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Discount description')),
                ('discount_type', models.CharField(choices=[('percent', 'Percentage'), ('fixed', 'Fixed Amount')], default='percent', help_text='Type of discount', max_length=10)),
                ('value', models.DecimalField(decimal_places=2, help_text='Discount value (percentage or fixed amount)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(choices=[('usd', 'USD'), ('eur', 'EUR')], default='usd', help_text='Currency for fixed amount discounts', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Item name', max_length=255)),
                ('description', models.TextField(help_text='Item description')),
                ('price', models.IntegerField(help_text='Price in smallest currency unit (cents for USD/EUR)', validators=[django.core.validators.MinValueValidator(1)])),
                ('currency', models.CharField(choices=[('usd', 'USD'), ('eur', 'EUR')], default='usd', help_text='Currency for the item', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tax name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Tax description')),
                ('tax_type', models.CharField(choices=[('percent', 'Percentage'), ('fixed', 'Fixed Amount')], default='percent', help_text='Type of tax', max_length=10)),
                ('value', models.DecimalField(decimal_places=2, help_text='Tax value (percentage or fixed amount)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(choices=[('usd', 'USD'), ('eur', 'EUR')], default='usd', help_text='Currency for fixed amount taxes', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discount', models.ForeignKey(blank=True, help_text='Discount applied to this order', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.discount')),
                ('items', models.ManyToManyField(help_text='Items in this order', related_name='orders', to='payments.item')),
                ('tax', models.ForeignKey(blank=True, help_text='Tax applied to this order', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.tax')),
            ],
        ),
    ]
